version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: task-api-postgres
    environment:
      POSTGRES_DB: task-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456